apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: argo
type: kubernetes.io/dockerconfigjson
data:
  # kubectl create secret docker-registry dockerhub-creds \
  #   --docker-server=https://index.docker.io/v1/ \
  #   --docker-username=wlanboy \
  #   --docker-password=TOKEN \
  #   -n argo --dry-run=client -o yaml
  .dockerconfigjson: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argo
type: Opaque
stringData:
  # GitHub Personal Access Token
  token: REPLACE_ME
