apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: kaniko
type: Opaque
stringData:
  # GitHub Personal Access Token (für private Repos)
  # Token benötigt: repo scope
  .git-credentials: |
    https://USERNAME:TOKEN@github.com
