apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirror
  namespace: argocd
spec:
  project: wlanboy

  source:
    repoURL: https://github.com/wlanboy/MirrorService.git
    targetRevision: main
    path: mirror-chart
    helm:
      releaseName: mirror
      valueFiles:
        - values.yaml
      valuesObject:
        extraVolumeMounts:
          - name: trust
            mountPath: /opt/trust
        extraVolumes:
          - name: trust
            secret:
              secretName: gmk-truststore
        extraEnv:
          - name: JAVA_TOOL_OPTIONS
            value: "-Djavax.net.ssl.trustStore=/opt/trust/gmk-truststore.p12 -Djavax.net.ssl.trustStorePassword=changeit"

  destination:
    name: gmk
    namespace: mirror

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
